name: Update blueprints version
description: Track blueprints update.
title: 'Update blueprints to generator-jhipster v8.x.x'
body:
  - type: markdown
    attributes:
      value: |
        Tracking update process
  - type: checkboxes
    id: blueprint
    attributes:
      label: Blueprint
      description: 'What blueprint do you want to update?'
      options:
        - label: generator-jhipster-native
        - label: generator-jhipster-migrate
        - label: generator-jhipster-entity-audit
        - label: generator-jhipster-ionic
        - label: generator-jhipster-react-native
        - label: generator-jhipster-micronaut
        - label: generator-jhipster-nodejs
        - label: generator-jhipster-quarkus
        - label: generator-jhipster-jooq
        - label: generator-jhipster-tenantview
        - label: generator-jhipster-es-reindexer
        - label: jhipster-dotnetcore
    validations:
      required: true
  - type: dropdown
    id: owner
    attributes:
      label: Owner
      description: 'What owner to use the repository as reference?'
      options:
        - jhipster
        - mshima
      default: 0
    validations:
      required: true
  - type: input
    id: extra_args
    attributes:
      label: Extra Args
      description: Extra Args
      placeholder: extra args
    validations:
      required: false
