name: Copyright Update

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Repository
        type: choice
        options:
          - mshima/generator-jhipster
          - mshima/generator-jhipster-native
          - mshima/generator-jhipster-migrate
          - mshima/generator-jhipster-entity-audit
          - mshima/generator-jhipster-jooq
          - mshima/generator-jhipster-tenantview
          - mshima/generator-jhipster-es-reindexer
          - mshima/jhipster-kotlin
      branch:
        type: string
        default: 'main'
        description: Branch

permissions:
  contents: read

jobs:
  build:
    name: copyright update
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          fetch-depth: 0
          token: ${{ secrets.CLASSIC_PAT }}
      - name: Find and Replace
        run: |
          grep -rlZE "Copyright 20[0-9]{2}-" . | xargs -0 sed -i -E "s/Copyright ([0-9]{4})-([0-9]{4})/Copyright \1-$(date +'%Y')/g"
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CLASSIC_PAT }}
          commit-message: 'Update copyright headers'
          title: 'Update Copyright Headers'
          body: 'This is an automated pull request to update the copyright headers'
          branch: 'copyright-date-update'
          author: 'Marcelo Shima <marceloshima@gmail.com>'
