name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Blueprint repository to be released
        type: choice
        options:
          - jhipster/generator-jhipster-native
          - jhipster/generator-jhipster-migrate
          - jhipster/generator-jhipster-entity-audit
          - jhipster/generator-jhipster-jooq
          - mshima/generator-jhipster-tenantview
          - mshima/generator-jhipster-es-reindexer
          - yeoman/generator
      extra-args:
        required: true
        type: string
        default: --increment minor --dry-run
        description: Type of npm version bump

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          fetch-depth: 0
          token: ${{ secrets.JHIPSTER_REPOSITORIES }}
      # - run: git config --unset-all http.https://github.com/.extraheader
      - run: git push -u origin
        env:
          GITHUB_TOKEN: ${{ secrets.JHIPSTER_REPOSITORIES }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      # - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: cat /home/runner/work/_temp/.npmrc
      - run: npx release-it --ci -VV ${{ inputs.extra-args }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.UPGRADE_PAT }}
