name: Release
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Blueprint repository to be released
        type: choice
        options:
          - jhipster/generator-jhipster-native
          - jhipster/generator-jhipster-migrate
          - jhipster/generator-jhipster-entity-audit
          - jhipster/generator-jhipster-jooq
          - mshima/generator-jhipster-tenantview
          - mshima/generator-jhipster-es-reindexer
          - yeoman/generator
      extra-args:
        required: true
        type: string
        default: --increment minor --dry-run
        description: Type of npm version bump

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH with a passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
      - name: git config
        run: |
          git config --global user.name "Marcelo Shima"
          git config --global user.email "marceloshima@gmail.com"
          ssh -T git@github.com || true
      - run: git clone git@github.com:${{ inputs.repository }}.git .
      # - run: git config --unset-all http.https://github.com/.extraheader
      - run: git push -u origin
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      # - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: cat /home/runner/work/_temp/.npmrc
      - run: npx release-it --ci -VV ${{ inputs.extra-args }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
