# This is a basic workflow to help you get started with Actions

name: Upgrade

on:
  workflow_dispatch:
    inputs:
      blueprint:
        required: true
        description: Blueprint repository to be upgraded
        type: choice
        options:
          - generator-jhipster-native
          - generator-jhipster-migrate
          - generator-jhipster-entity-audit
          - generator-jhipster-ionic
          - generator-jhipster-react-native
          - generator-jhipster-micronaut
          - generator-jhipster-nodejs
          - generator-jhipster-quarkus
          - generator-jhipster-jooq
          - generator-jhipster-tenantview
          - generator-jhipster-es-reindexer
          - jhipster-dotnetcore
      owner:
        default: jhipster
        description: Repository owner
      extra-args:
        default: --github-workflows --skip-workflows
        description: Extra arguments
  workflow_call:
    inputs:
      blueprint:
        type: string
        required: true
        description: Blueprint repository to be upgraded
      owner:
        type: string
        default: jhipster
        description: Repository owner
      extra-args:
        type: string
        default: --github-workflows --skip-workflows
        description: Extra arguments
    outputs:
      pull-request-url:
        description: "PR link"
        value: ${{ jobs.upgrade.outputs.pull-request-url }}

permissions:
  contents: read

jobs:
  upgrade:
    name: Upgrade ${{ inputs.blueprint }} to generator-jhipster@${{ inputs.ref }}
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.blueprint }}
    outputs:
      pull-request-url: ${{ steps.create-pull-request.outputs.pull-request-url }}
    steps:
      # Use git repository due to https://github.com/npm/cli/issues/6984
      - uses: actions/checkout@v4
        with:
          repository: mshima/generator-jhipster
          ref: blueprint-workflows
          path: generator-jhipster
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.blueprint }}
          path: ${{ inputs.blueprint }}
          token: ${{ secrets.CLASSIC_PAT }}
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: 20
          binary-dir: ${{ github.workspace }}/generator-jhipster/bin
      - run: npm ci --ignore-scripts
        working-directory: ${{ github.workspace }}/generator-jhipster
      - run: echo "version=$(jhipster.cjs --version)" >> "$GITHUB_OUTPUT"
        id: version
      - name: upgrade to generator-jhipster@${{ steps.version.outputs.version }}
        run: |
          npm uninstall eslint-plugin-import eslint-config-airbnb-base
          jhipster.cjs generate-blueprint --force --skip-workflows --ignore-existing-generators --recreate-package-lock --commit-msg 'update generator-jhipster to ${{ inputs.ref }}' ${{ inputs.extra-args }}
          npm run prettier-format || true
          npm run lint-fix || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: create-pull-request
        with:
          path: ${{ github.workspace }}/${{ inputs.blueprint }}
          push-to-fork: ${{ 'mshima' != inputs.owner && format('{0}/{1}', 'mshima', inputs.blueprint) || '' }}
          # Use CLASSIC_PAT for PRs permission
          token: ${{ secrets.CLASSIC_PAT }}
          # Use UPGRADE_PAT for workflow permission
          git-token: ${{ secrets.UPGRADE_PAT }}
          commit-message: Update generator-jhipster to ${{ steps.version.outputs.version }}
          title: Update generator-jhipster to ${{ steps.version.outputs.version }}
          body: This is an automated pull request to update generator-jhipster
          branch: generator-jhipster-${{ steps.version.outputs.version }}
