# This is a basic workflow to help you get started with Actions

name: Upgrade

on:
  workflow_dispatch:
    inputs:
      blueprint:
        required: true
        description: Blueprint repository to be upgraded
        type: choice
        options:
          - generator-jhipster-native
          - generator-jhipster-migrate
          - generator-jhipster-entity-audit
          - generator-jhipster-ionic
          - generator-jhipster-react-native
          - generator-jhipster-micronaut
          - generator-jhipster-nodejs
          - generator-jhipster-quarkus
          - generator-jhipster-jooq
          - generator-jhipster-tenantview
          - generator-jhipster-es-reindexer
          - jhipster-dotnetcore
      owner:
        default: jhipster
        description: Repository owner
      fork-owner:
        default: mshima
        description: Fork repository owner
      generator-jhipster:
        default: 'generator-jhipster@latest'
        description: JHipster spec
      extra-args:
        default: --github-workflows
        description: Extra arguments

permissions:
  contents: read

jobs:
  upgrade:
    name: Upgrade ${{ inputs.blueprint }} to generator-jhipster@${{ inputs.generator-jhipster }}
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.blueprint }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.blueprint }}
          path: ${{ inputs.blueprint }}
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: 20
      - run: npm install -g ${{ inputs.generator-jhipster }}
      - run: echo "version=$(jhipster --version)" >> "$GITHUB_OUTPUT"
        id: version
      - name: upgrade to generator-jhipster@${{ steps.version.outputs.version }}
        run: |
          jhipster generate-blueprint --force ${{ inputs.extra-args }}
          rm -rf node_modules package-lock.json
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: ${{ github.workspace }}/${{ inputs.blueprint }}
          push-to-fork: ${{ inputs.fork-owner != inputs.owner && format('{0}/{1}', inputs.fork-owner, inputs.blueprint) || '' }}
          token: ${{ secrets.UPGRADE_PAT }}
          commit-message: Update generator-jhipster to ${{ steps.version.outputs.version }}
          title: Update generator-jhipster to ${{ steps.version.outputs.version }}
          body: This is an automated pull request to update generator-jhipster
          branch: generator-jhipster-${{ steps.version.outputs.version }}
